-- Esquema de base de datos para BioPractor.
-- Ejecuta este archivo completo en el SQL Editor de tu proyecto de Supabase
-- (https://supabase.com/dashboard/project/_/sql/new).

create extension if not exists "pgcrypto";

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  reference text not null default '',
  category_slugs text[] not null default '{}',
  price integer not null default 0,
  short_description text not null default '',
  description text not null default '',
  images text[] not null default '{}',
  featured boolean not null default false,
  archived boolean not null default false,
  views integer not null default 0,
  whatsapp_clicks integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_archived_idx on products (archived);
create index if not exists products_category_slugs_idx on products using gin (category_slugs);

-- Incrementos atómicos (evitan condiciones de carrera con muchas visitas a la vez).
create or replace function increment_product_view(p_slug text)
returns void as $$
  update products set views = views + 1
  where slug = p_slug and archived = false;
$$ language sql;

create or replace function increment_whatsapp_click(p_slug text)
returns void as $$
  update products set whatsapp_clicks = whatsapp_clicks + 1
  where slug = p_slug and archived = false;
$$ language sql;

-- Catalogo real de BioPractor (153 productos), generado a partir de:
--   - "Listado productos 2026 (3).xlsx" (precios actualizados por referencia)
--   - "Catalogo AlmaVida actualizado (1).pdf" (nombres, descripciones y fotos)
-- Las fotos viven en public/products/<slug>.webp dentro del proyecto Next.js.
insert into products (slug, name, reference, category_slugs, price, short_description, description, images)
values
  ('ashwagandha-colon-max', 'Ashwagandha (Colon max)', 'CM-14', array['energia','sueno-estres','digestion'], 38000, 'Reduce el estrés y la ansiedad', 'Reduce el estrés y la ansiedad, Ayuda al equilibrio del cortisol, Mejora energía y resistencia, Favorece el descanso y bienestar Presentación: 100 capsulas blandas. INVIMA: RSA-2944-2025.', array['/products/ashwagandha-colon-max.webp']),
  ('omega-3-6-9-greensofg', 'Omega 3, 6, 9 greensofg', 'LN-34', array['energia'], 43000, 'Aumenta la concentración y el rendimiento mental', 'Aumenta la concentración y el rendimiento mental. Reduce la inflamación y ayuda a aliviar dolor articular. Presentación: 100 capsulas blandas. INVIMA: RSA-0034378-2024.', array['/products/omega-3-6-9-greensofg.webp']),
  ('circulan', 'Circulan', 'IS-50', array['cardiovascular'], 26000, 'Apoya la circulación sanguínea', 'Apoya la circulación sanguínea, Contribuye a la salud cardiovascular, Apoya el sistema inmune, Ayuda a la depuración del organismo, Puede apoyar el co... Presentación: 500ml liquido. INVIMA: RSA-0023314-2023.', array['/products/circulan.webp']),
  ('vitamina-d3-k2-bolsa', 'Vitamina D3 & K2 Bolsa', 'PS-137', array['articulaciones-huesos','inmunidad','cardiovascular'], 39000, 'Ayuda a una mejor absorción del calcio', 'Ayuda a una mejor absorción del calcio, Fortalece huesos y dientes, Apoya el sistema inmunológico, Contribuye a la salud cardiovascular, Ayuda a que e... Presentación: 90 Capsula. INVIMA: NSA-2365-2025.', array['/products/vitamina-d3-k2-bolsa.webp']),
  ('vitamina-c-prosimpo', 'Vitamina C prosimpo', 'NL-122', array['colageno-belleza','articulaciones-huesos','digestion','inmunidad'], 25000, 'Refuerza el sistema inmunológico (vitamina C)', 'Refuerza el sistema inmunológico (vitamina C). Ayuda a la producción de colágeno para piel, uñas y articulaciones. Contribuye a la absorción del hierro. Apoya la digestión y salud intestinal gracias a la fibra de naranja. Efecto antioxidante, ayuda a combatir... Presentación: 380ml liquido. INVIMA: RSA-0026730-2024.', array['/products/vitamina-c-prosimpo.webp']),
  ('femivid', 'Femivid', 'IM-40', array['energia','colageno-belleza','ninos'], 14000, 'Fortalece cabello', 'Fortalece cabello, piel y uñas (biotina), Apoya la formación de glóbulos rojos (ácido fólico + B12) , Aumenta energía y vitalidad (vitaminas B), Refuerza el sistema inmune (zinc y selenio),. Apoya el sistema nervioso, Contribuye al bienestar femenino Presentación: 30 Tabletas. INVIMA: SD2011-0002157.', array['/products/femivid.webp']),
  ('pr-polizan', 'Pr Polizan', 'NM-123', array['inmunidad'], 21000, 'Refuerza el sistema inmunológico', 'Refuerza el sistema inmunológico, Ayuda a aliviar gripa, tos y dolor de garganta, Descongestiona las vías respiratorias (eucalipto), Tiene acción anti... Presentación: Miel. INVIMA: RSVA16I71614.', array['/products/pr-polizan.webp']),
  ('factor-de-transferencia', 'Factor de transferencia', 'NL-113', array['inmunidad'], 25000, 'Fortalece el sistema inmunológico', 'Fortalece el sistema inmunológico, Apoya las defensas naturales del cuerpo, Ayuda en la respuesta ante infecciones, Favorece la recuperación y el bien... Presentación: 380ml liquido. INVIMA: RSA-0026730-2023.', array['/products/factor-de-transferencia.webp']),
  ('producto-ch-23', 'Producto CH-23', 'CH-23', array['bienestar-general'], 15000, '[CONTENIDO PENDIENTE: descripcion]', '[CONTENIDO PENDIENTE: descripcion completa de este producto]', array[]::text[]),
  ('reuma-flex', 'Reuma flex', 'CL-8', array['articulaciones-huesos'], 28000, 'Ayuda a aliviar dolor articular y muscular', 'Ayuda a aliviar dolor articular y muscular, Apoya el manejo de artritis y artrosis, Reduce inflamación y rigidez, Mejora la movilidad, Apoya el bienestar osteomuscular Presentación: 30 Capsulas. INVIMA: PFT2023-0002132-R1.', array['/products/reuma-flex.webp']),
  ('producto-ch-20', 'Producto CH-20', 'CH-20', array['bienestar-general'], 31000, '[CONTENIDO PENDIENTE: descripcion]', '[CONTENIDO PENDIENTE: descripcion completa de este producto]', array[]::text[]),
  ('sure', 'Sure', 'CM-26', array['energia','inmunidad','ninos'], 30000, 'Aporta nutrición completa y balanceada', 'Aporta nutrición completa y balanceada,Ayuda al crecimiento y desarrollo,Contribuye al fortalecimiento del sistema inmunológico,Apoya la energía y vit... Presentación: 600gr Polvo. INVIMA: NSA-0010776-2021.', array['/products/sure.webp']),
  ('oregano-capsulas-colon-max-sas', 'Oregano cápsulas Colon max sas', 'CM-24', array['digestion'], 40000, 'mejora la digestión y disminuye la inflamación ayuda a aliviar gripe', 'mejora la digestión y disminuye la inflamación ayuda a aliviar gripe, tos y molestias respiratorias Presentación: 100 capsulas blandas. INVIMA: RSA-2944-2025.', array['/products/oregano-capsulas-colon-max-sas.webp']),
  ('colagecol-colageno-hidrolizado-1000gr', 'Colagecol + colageno hidrolizado 1000gr', 'CO-237', array['colageno-belleza','articulaciones-huesos','inmunidad'], 39000, 'Colágeno hidrolizado con resveratrol', 'Colágeno hidrolizado con resveratrol, cúrcuma, biotina, vitamina E y calcio, que apoya piel, cabello, uñas, articulaciones, huesos, antioxidantes y regeneración celular. Presentación: 1000 Polvo. INVIMA: RSA-0030470-2024.', array['/products/colagecol-colageno-hidrolizado-1000gr.webp']),
  ('inositol-efervescente', 'Inositol efervescente', 'CO-11', array['hormonal'], 38000, 'Apoya el equilibrio hormonal', 'Apoya el equilibrio hormonal, Ayuda en casos de ovario poliquístico (SOP), Contribuye a regular el ciclo menstrual, Mejora la sensibilidad a la insuli... Presentación: 120 Tabletas. INVIMA: RSA-2121-2025.', array['/products/inositol-efervescente.webp']),
  ('perlas-de-ajo-rogoff', 'Perlas de ajo Rogoff', 'IM-42', array['cardiovascular'], 16000, 'Apoya la salud cardiovascular', 'Apoya la salud cardiovascular, Ayuda a mantener niveles normales de colesterol y presión, Favorece la circulación sanguínea, Refuerza el sistema inmun... Presentación: 180 Tabletas. INVIMA: SD2017-0003988.', array['/products/perlas-de-ajo-rogoff.webp']),
  ('valeriana-toronjil-pasiflora', 'Valeriana+toronjil+pasiflora', 'IM-43', array['sueno-estres','digestion'], 17000, 'Ayuda a conciliar el sueño Reduce el estrés', 'Ayuda a conciliar el sueño Reduce el estrés, la ansiedad y el nerviosismo, Favorece la relajación mental, Ayuda a calmar palpitaciones de origen nervi... Presentación: 60ml Liquido. INVIMA: PFM2020-0002729.', array['/products/valeriana-toronjil-pasiflora.webp']),
  ('trigosamine', 'Trigosamine', 'IM-47', array['colageno-belleza','articulaciones-huesos'], 35000, 'Fortalece huesos y articulaciones', 'Fortalece huesos y articulaciones, Ayuda a reducir dolor y rigidez articular, Mejora la movilidad, Apoya la salud muscular, Contribuye a la absorción de calcio, Favorece piel, uñas y cartílagos Presentación: 90 Capsulas. INVIMA: SD2013-0002853.', array['/products/trigosamine.webp']),
  ('colaget', 'Colaget', 'IS-48', array['energia','colageno-belleza','articulaciones-huesos'], 28000, 'Apoya huesos y articulaciones', 'Apoya huesos y articulaciones, ayudando a mantener su resistencia y movilidad,Contribuye a la salud de la piel, uñas y cabello, mejorando su aparienci... Presentación: 700gr Polvo. INVIMA: RSA-0036041-2025.', array['/products/colaget.webp']),
  ('multicevita', 'Multicevita', 'IM-45', array['energia','colageno-belleza'], 9000, 'apoya la energía', 'apoya la energía, el sistema nervioso y la formación de glóbulos rojos, contribuye a la salud del cabello, piel y uñas, apoyan el sistema inmune y la función tiroidea. Presentación: 20 Tabletas. INVIMA: SD2011-0002157.', array['/products/multicevita.webp']),
  ('flexdl', 'Flexdl', 'IM-41', array['sueno-estres','articulaciones-huesos'], 17000, 'Alivia dolores musculares y articulares', 'Alivia dolores musculares y articulares, Ayuda en contracturas, golpes y sobrecargas, Efecto relajante y antiinflamatorio, Mejora la movilidad al usar... Presentación: 80g Gel. INVIMA: NSOC00708-20CO.', array['/products/flexdl.webp']),
  ('kinder-plus', 'Kinder Plus', 'HN-285', array['energia','inmunidad'], 33000, 'Apoyo a la salud ocular', 'Apoyo a la salud ocular, Prevención de la anemia y apoyo a la energía, Fortalecimiento del sistema inmunológico y el crecimiento Presentación: 1000ml liquido. INVIMA: RSA-0023191-2023.', array['/products/kinder-plus.webp']),
  ('mega-kids', 'Mega-kids', 'HN-284', array['energia','inmunidad','ninos'], 32000, 'Previene la anemia y combate la fatiga', 'Previene la anemia y combate la fatiga, Fortalece el sistema inmunológico, Apoya el desarrollo cognitivo y del sistema nervioso Presentación: 1000ml liquido. INVIMA: RSA-0028125-2023.', array['/products/mega-kids.webp']),
  ('fibraplus', 'Fibraplus', 'IS-54', array['digestion','peso-metabolismo'], 26000, 'Mejora el tránsito intestinal', 'Mejora el tránsito intestinal, Ayuda a prevenir y aliviar el estreñimiento, Favorece la limpieza digestiva, Aporta fibra natural y vitaminas, Apoya la digestión y reduce la hinchazón, Contribuye al control del peso Presentación: 500ml liquido. INVIMA: RSA-0023314-2023.', array['/products/fibraplus.webp']),
  ('fos-probioticos-y-zinc', 'Fos probioticos y zinc', 'LN-1', array['digestion'], 45000, 'Ayuda a mantener el equilibrio del pH íntimo', 'Ayuda a mantener el equilibrio del pH íntimo, Apoya la salud vaginal y reduce el mal olor, Mejora la flora intestinal y vaginal, Ayuda a digerir la la... Presentación: 100 Capsulas blandas. INVIMA: RSA-0034378-2024.', array['/products/fos-probioticos-y-zinc.webp']),
  ('proxx', 'Proxx', 'IS-58', array['inmunidad'], 25000, 'Apoya las defensas del organismo', 'Apoya las defensas del organismo, Ayuda a aliviar garganta y vías respiratorias, Fuente natural de vitamina C (camu camu), Efecto antioxidante, Contri... Presentación: 500ml liquido. INVIMA: RSA-0023314-2024.', array['/products/proxx.webp']),
  ('clorofila', 'Clorofila', 'LN-63', array['energia','digestion'], 30000, 'Ayuda a desintoxicar el organismo', 'Ayuda a desintoxicar el organismo, Apoya la digestión y el funcionamiento intestinal, Contribuye a la oxigenación y vitalidad del cuerpo Presentación: 1000ml liquido. INVIMA: RSA-0025193-2023.', array['/products/clorofila.webp']),
  ('triple-maca', 'Triple Maca', 'NH-103', array['energia','hormonal'], 34000, 'Apoya la energía y vitalidad', 'Apoya la energía y vitalidad, Contribuye al rendimiento físico y mental, Ayuda al equilibrio hormonal, Favorece la libido y resistencia Presentación: 1000ml liquido. INVIMA: RSA-0026005-2023.', array['/products/triple-maca.webp']),
  ('melena-de-leon-natural-health', 'Melena de león (natural health)', 'NH-105', array['bienestar-general'], 34000, 'Apoya la memoria y la concentración', 'Apoya la memoria y la concentración. Contribuye a la salud del sistema nervioso. Favorece la claridad mental y el enfoque. Presentación: 100 Tabletas. INVIMA: RSA-0034199-2024.', array['/products/melena-de-leon-natural-health.webp']),
  ('vitamina-e-selenio', 'Vitamina E + Selenio', 'LN-84', array['colageno-belleza','inmunidad','cardiovascular'], 43000, 'Potente antioxidante (protege las células)', 'Potente antioxidante (protege las células). Refuerza el sistema inmunológico. Apoya la salud cardiovascular. Ayuda a la salud de la piel y envejecimie... Presentación: 100 Capsulas blandas. INVIMA: RSA-0034378-2024.', array['/products/vitamina-e-selenio.webp']),
  ('lim-pichn-polvo', 'Lim-pichn Polvo', 'LN-67', array['digestion'], 8000, 'Mejora el tránsito intestinal', 'Mejora el tránsito intestinal, Ayuda a aliviar el estreñimiento, Aporta fibra natural (manzana, papaya, pitaya, ciruela, psyllium), Favorece la digest... Presentación: 30g Polvo. INVIMA: RSA-0011637-2021.', array['/products/lim-pichn-polvo.webp']),
  ('zarmit', 'Zarmit', 'LN-71', array['digestion'], 14000, 'Apoya la depuración del organismo', 'Apoya la depuración del organismo, Favorece la función digestiva y hepática (alcachofa y ruibarbo), Ayuda a reducir gases y pesadez, Contribuye al dre... Presentación: 375ml Liquido. INVIMA: RSA-0025193-2023.', array['/products/zarmit.webp']),
  ('te-matcha-natural-health', 'Té Matcha Natural Health', 'NH-102', array['energia','digestion','peso-metabolismo'], 34000, 'Aumenta energía y concentración (té matcha)', 'Aumenta energía y concentración (té matcha). Ayuda a acelerar el metabolismo. Mejora el enfoque y el rendimiento mental, Apoya la digestión y el equil... Presentación: 100 Tabletas. INVIMA: RSA-0039199-2024.', array['/products/te-matcha-natural-health.webp']),
  ('lim-pichn-60ml', 'Lim-pichn 60ml', 'LN-66', array['digestion'], 8000, 'Mejora el tránsito intestinal', 'Mejora el tránsito intestinal, Ayuda a aliviar el estreñimiento, Aporta fibra natural (manzana, papaya, pitaya, ciruela, psyllium), Favorece la digest... Presentación: 60ml Liquido. INVIMA: RSA-0011706-2021.', array['/products/lim-pichn-60ml.webp']),
  ('gomas-de-magnesio-y-potasio-de-natural-health', 'Gomas de Magnesio y Potasio de Natural Health', 'NH-185', array['energia'], 38000, 'Apoya la función muscular', 'Apoya la función muscular. Contribuye a mantener el equilibrio de electrolitos. Ayuda a mejorar la energía y reducir la fatiga. Presentación: 60 Gomas. INVIMA: RSA-0030470-2024.', array['/products/gomas-de-magnesio-y-potasio-de-natural-health.webp']),
  ('gomas-de-vinagre-de-manzana-natural-health', 'Gomas de vinagre de manzana Natural Health', 'NH-213', array['digestion','peso-metabolismo'], 27000, '"Apoya la digestión y el metabolismo', '"Apoya la digestión y el metabolismo. Contribuye al control del apetito. Favorece el equilibrio de los niveles de azúcar en sangre. Presentación: 30 gomas. INVIMA: RSA-0030470-2024.', array['/products/gomas-de-vinagre-de-manzana-natural-health.webp']),
  ('producto-nh-173', 'Producto NH-173', 'NH-173', array['bienestar-general'], 33000, '[CONTENIDO PENDIENTE: descripcion]', '[CONTENIDO PENDIENTE: descripcion completa de este producto]', array[]::text[]),
  ('goma-de-ashwandha-con-magnesio-y-vitamina-c-natural-health', 'Goma de Ashwandha con Magnesio y Vitamina C Natural Health', 'NH-181', array['energia','sueno-estres','inmunidad'], 37000, 'Ayuda a reducir el estrés y la ansiedad', 'Ayuda a reducir el estrés y la ansiedad. Contribuye a aumentar la energía. Apoya el sistema inmunológico. Presentación: 60 Gomas. INVIMA: RSA-0030470-2024.', array['/products/goma-de-ashwandha-con-magnesio-y-vitamina-c-natural-health.webp']),
  ('bisglicinato-natural-health', 'Bisglicinato Natural Health', 'NH-230', array['sueno-estres'], 34000, 'Favorece la relajación y mejora el sueño', 'Favorece la relajación y mejora el sueño, Ayuda a reducir el estrés y la ansiedad, Contribuye a la salud muscular y evita calambres Presentación: 100 Tabletas Frasco. INVIMA: RSA-0034199-2024.', array['/products/bisglicinato-natural-health.webp']),
  ('gomas-de-glucosamina-natural-health', 'Gomas de Glucosamina Natural Health', 'NH-183', array['articulaciones-huesos'], 41000, 'Ayuda a proteger el cartílago', 'Ayuda a proteger el cartílago. Favorece la lubricación de las articulaciones. Apoya la salud de los huesos. Presentación: 60 Gomas. INVIMA: NSA-3192-2025.', array['/products/gomas-de-glucosamina-natural-health.webp']),
  ('betaglucano-de-ganoderma', 'Betaglucano de ganoderma', 'NH-91', array['energia','inmunidad'], 34000, 'Refuerza el sistema inmunológico', 'Refuerza el sistema inmunológico, Ayuda a la respuesta antiinflamatoria, Aumenta energía y vitalidad, Apoya las defensas naturales del cuerpo, Contrib... Presentación: 100 Capsulas blandas. INVIMA: RSA-0034199-2024.', array['/products/betaglucano-de-ganoderma.webp']),
  ('gomas-de-inositol-de-natural-health', 'Gomas de Inositol de Natural Health', 'NH-184', array['hormonal'], 37000, 'Ayuda al equilibrio hormonal', 'Ayuda al equilibrio hormonal. Mejora la sensibilidad a la insulina. Contribuye al bienestar emocional. Presentación: 60 Gomas. INVIMA: NSA-3192-2025.', array['/products/gomas-de-inositol-de-natural-health.webp']),
  ('gomas-magnesio-melatonina-de-natural-health', 'Gomas Magnesio Melatonina de Natural Health', 'NH-186', array['sueno-estres'], 39000, 'Ayuda a mejorar la calidad del sueño', 'Ayuda a mejorar la calidad del sueño. Contribuye a reducir el insomnio ocasional. Apoya el bienestar del sistema nervioso. Presentación: 60 Gomas. INVIMA: NSA-3192-2025.', array['/products/gomas-magnesio-melatonina-de-natural-health.webp']),
  ('nad-con-resveratrol-natural-health', 'Nad+ con resveratrol (Natural Health)', 'NH-97', array['energia','colageno-belleza','inmunidad'], 36000, 'Apoya la energía celular', 'Apoya la energía celular, Favorece la concentración y claridad mental, Apoya el envejecimiento saludable, Acción antioxidante (resveratrol) Presentación: 100 Tabletas. INVIMA: RSA-0034199-2024.', array['/products/nad-con-resveratrol-natural-health.webp']),
  ('ginkgo-biloba', 'Ginkgo biloba', 'NL-115', array['cardiovascular'], 35000, 'Apoya la memoria y la concentración', 'Apoya la memoria y la concentración, favoreciendo la función cognitiva,Mejora la circulación sanguínea, especialmente a nivel cerebral y periférico,Co... Presentación: 800gr Polvo. INVIMA: RSAD12174011.', array['/products/ginkgo-biloba.webp']),
  ('prostamax', 'Prostamax', 'NL-117', array['inmunidad'], 25000, 'Apoya la salud de la próstata', 'Apoya la salud de la próstata, Ayuda al sistema urinario, Antioxidante (licopeno, arándanos y granada), Contribuye a reducir inflamación, Apoya defens... Presentación: 380ml liquido. INVIMA: RSA-0026730-2023.', array['/products/prostamax.webp']),
  ('producto-nl-18', 'Producto NL-18', 'NL-18', array['bienestar-general'], 32000, '[CONTENIDO PENDIENTE: descripcion]', '[CONTENIDO PENDIENTE: descripcion completa de este producto]', array[]::text[]),
  ('vino-cerebral-prosimpo', 'Vino Cerebral prosimpo', 'NL-120', array['energia'], 25000, 'Apoya la memoria', 'Apoya la memoria, concentración y rendimiento mental Ayuda a reducir cansancio físico y mental Contribuye a la energía y vitalidad (maca y ginseng), A... Presentación: 380ml liquido. INVIMA: RSA-0026730-2023.', array['/products/vino-cerebral-prosimpo.webp']),
  ('torovitol', 'Torovitol', 'NP-130', array['energia'], 34000, 'Aporta energía y vitalidad', 'Aporta energía y vitalidad, Apoya el sistema nervioso y el rendimiento físico, Contribuye a reducir el cansancio y la fatiga Presentación: 1000ml liquido. INVIMA: RSA-0029174-2023.', array['/products/torovitol.webp']),
  ('glucosamina-liquida-x1000ml', 'Glucosamina liquida x1000ml', 'NL-208', array['energia','articulaciones-huesos','inmunidad'], 31000, 'Apoya la salud de las articulaciones gracias a la glucosamina', 'Apoya la salud de las articulaciones gracias a la glucosamina, el condroitín y el calcio, ayudando a mantener la movilidad y reducir el desgaste del cartílago. Contribuye al fortalecimiento de huesos y tejidos conectivos, favoreciendo una mejor estructura ósea y resistencia física. Aporta antioxidantes y vitaminas que ayudan a proteger las células, fortalecer el sistema inmunológico y mejorar el bienestar general. Presentación: 1000ml liquido. INVIMA: RSA-0026730-2023.', array['/products/glucosamina-liquida-x1000ml.webp']),
  ('bililax', 'Bililax', 'NP-257', array['digestion','cardiovascular'], 34000, 'Optimiza tu digestión', 'Optimiza tu digestión, Protege tu hígado, Apoya el control del colesterol Presentación: 1.000ml liquido. INVIMA: RSA-0029174-2023.', array['/products/bililax.webp']),
  ('chanca-piedra', 'Chanca Piedra', 'NP-127', array['bienestar-general'], 33000, 'Apoya la salud renal: Tradicionalmente usado para ayudar a prevenir y eliminar cálculos renales (piedras en los riñones)', 'Apoya la salud renal: Tradicionalmente usado para ayudar a prevenir y eliminar cálculos renales (piedras en los riñones). Favorece la función del híga... Presentación: 1000ml liquido. INVIMA: RSA-0008686-2019.', array['/products/chanca-piedra.webp']),
  ('oil-of-oregano-frasco', 'Oil of oregano frasco', 'PS-133', array['digestion','inmunidad'], 45000, 'Potente antibacteriano y antimicrobiano natural', 'Potente antibacteriano y antimicrobiano natural, Apoya el sistema inmunológico, Ayuda a combatir hongos y parásitos intestinales, Contribuye a la salu... Presentación: 100 Capsulas. INVIMA: NSA-2365-2025.', array['/products/oil-of-oregano-frasco.webp']),
  ('zarzaparrilla-natural-medy', 'Zarzaparrilla Natural Medy', 'NM-263', array['colageno-belleza'], 34000, 'Depuración Natural: Ayuda a limpiar el cuerpo', 'Depuración Natural: Ayuda a limpiar el cuerpo, Piel Saludable: Contribuye a una piel más sana, Efecto Diurético: Favorece la eliminación de líquidos Presentación: 360 ml liquido. INVIMA: SD2019-0004448.', array['/products/zarzaparrilla-natural-medy.webp']),
  ('vitacerebrina', 'VItacerebrina', 'NL-217', array['energia'], 30000, 'Aumento de energía natural', 'Aumento de energía natural, Fortalecimiento del sistema inmune, Apoyo a la salud cognitiva Presentación: 1000ml liquido. INVIMA: RSA-0026730-2023.', array['/products/vitacerebrina.webp']),
  ('isoflavonas-de-soya-prame', 'Isoflavonas de soya Prame', 'PS-245', array['hormonal','cardiovascular'], 25000, 'Alivio de síntomas de la menopausia', 'Alivio de síntomas de la menopausia, Equilibrio hormonal natural, Protección ósea y cardiovascular Presentación: 30 Capsulas. INVIMA: RSA-0032589-2024.', array['/products/isoflavonas-de-soya-prame.webp']),
  ('omega-3-con-curcuma-y-pimienta-negra', 'Omega 3 con curcuma y pimienta negra', 'PS-271', array['digestion','cardiovascular'], 44000, 'Apoya el cerebro y la memoria', 'Apoya el cerebro y la memoria, Beneficios para el corazón, Efecto antiinflamatorio, Apoyo digestivo Presentación: 100 capsulas. INVIMA: RSA-0036530-2025.', array['/products/omega-3-con-curcuma-y-pimienta-negra.webp']),
  ('psyllium', 'Psyllium', 'VC-163', array['digestion','peso-metabolismo'], 32000, 'Mejora el tránsito intestinal y combate el estreñimiento', 'Mejora el tránsito intestinal y combate el estreñimiento, Alto contenido de fibra, ayuda a depurar el colon, Aporta saciedad, útil para control de pes... Presentación: 450gr Polvo. INVIMA: NSA-0010829-2021.', array['/products/psyllium.webp']),
  ('g4-str1', 'G4-str1', 'SU-144', array['digestion'], 26000, 'Mejora la digestión (manzanilla', 'Mejora la digestión (manzanilla, menta y mejorana), Ayuda a desinflamar y aliviar malestar estomacal , Apoya la salud intestinal (aloe vera y papaya),... Presentación: 360ml Liquido. INVIMA: RSA-0014366-2021.', array['/products/g4-str1.webp']),
  ('fibra-de-flor-de-jamaica', 'Fibra de Flor de Jamaica', 'VC-241', array['bienestar-general'], 32000, 'Suplemento en polvo a base de linaza con mezcla natural de alcachofa', 'Suplemento en polvo a base de linaza con mezcla natural de alcachofa, pitahaya, té verde, noni, spirulina y flor de jamaica. Ideal para apoyar la dige... Presentación: Polvo. INVIMA: NSA-0010829-2021.', array['/products/fibra-de-flor-de-jamaica.webp']),
  ('glicinato-de-magnesio-satoomi', 'Glicinato de Magnesio Satoomi', 'PS-274', array['sueno-estres'], 42000, 'Mejora de la calidad del sueño', 'Mejora de la calidad del sueño, Apoyo a la salud muscular, Promoción de la calma mental Presentación: 100 capsulas. INVIMA: RSA-0036530-2025.', array['/products/glicinato-de-magnesio-satoomi.webp']),
  ('complejo-b', 'Complejo B', 'PS-176', array['energia','inmunidad'], 18000, 'Ayuda a convertir los alimentos en energía', 'Ayuda a convertir los alimentos en energía, apoyando el rendimiento diario. Contribuye al buen funcionamiento del sistema nervioso. Favorece la salud del sistema inmunológico gracias a su combinación de vitaminas y zinc. Presentación: 30 capsulas. INVIMA: RSA-0037262-2025.', array['/products/complejo-b.webp']),
  ('magnesium-complex-12-en-1', 'Magnesium complex 12 en 1', 'VW-157', array['energia','sueno-estres','articulaciones-huesos'], 40000, 'reduce calambres', 'reduce calambres, tensión y dolor muscular aumenta la energía y fortalece huesos y articulaciones Presentación: 100 capsulas blandas. INVIMA: NSA-2040-2025.', array['/products/magnesium-complex-12-en-1.webp']),
  ('liposomal-vitamina-c', 'Liposomal vitamina c', 'VW-151', array['colageno-belleza','articulaciones-huesos','inmunidad'], 40000, 'Refuerza el sistema inmunológico', 'Refuerza el sistema inmunológico, Potente acción antioxidante (protege las células), Ayuda a la producción de colágeno (piel, uñas y articulaciones),... Presentación: 100 Gomas. INVIMA: NSA-0341-2026.', array['/products/liposomal-vitamina-c.webp']),
  ('creatine-vitalherb', 'Creatine vitalherb', 'VW-154', array['energia'], 43000, 'Aumenta la fuerza y potencia muscular', 'Aumenta la fuerza y potencia muscular, Mejora el rendimiento físico en entrenamientos intensos, Ayuda a ganar masa muscular, Favorece una mejor recuperación post-entreno, Apoya la resistencia y energía Presentación: 500gr Polvo. INVIMA: RSA-2549-2025.', array['/products/creatine-vitalherb.webp']),
  ('candida-cleanse-vitalworld', 'Candida cleanse Vitalworld', 'VW-153', array['digestion'], 37000, 'Apoya el equilibrio natural de la flora intestinal', 'Apoya el equilibrio natural de la flora intestinal, Favorece una digestión más ligera y confortable, Contribuye al bienestar digestivo diario, Apoya l... Presentación: 60 Capsulas. INVIMA: NSA-2862-2025.', array['/products/candida-cleanse-vitalworld.webp']),
  ('7-colagenos', '7 Colagenos', 'WN-250', array['energia','colageno-belleza','articulaciones-huesos'], 32000, 'Ayuda a mejorar la elasticidad', 'Ayuda a mejorar la elasticidad, firmeza e hidratación de la piel, Fortalece los cartílagos, huesos y articulaciones, promoviendo la movilidad, Contribuye al buen funcionamiento del cuerpo y aporta energía Presentación: 1.100 ml Liquido. INVIMA: RSA-0021537-2022.', array['/products/7-colagenos.webp']),
  ('shilajit-capsulas', 'Shilajit cápsulas', 'VW-160', array['energia','hormonal'], 42000, 'Aumenta la energía', 'Aumenta la energía, vitalidad y resistencia, Apoya el rendimiento físico y mental, Maca, borojó, chontaduro y guaraná: ayudan a la libido y reducen el... Presentación: 100 Capsula. INVIMA: RSA-0036530-2025.', array['/products/shilajit-capsulas.webp']),
  ('magnesium-complex-8-en-1', 'Magnesium complex 8 en 1', 'VW-158', array['energia','sueno-estres'], 40000, 'Reduce el estrés y mejora el sueño', 'Reduce el estrés y mejora el sueño .Disminuye calambres y dolores musculares. Aporta energía y mejora el ánimo. Presentación: 100 capsulas blandas. INVIMA: NSA-2040-2025.', array['/products/magnesium-complex-8-en-1.webp'])
on conflict (slug) do nothing;

-- ============================================================
-- Citas / solicitudes de terapias a domicilio
-- (se llenan cuando alguien reserva desde el sitio; el dueño las
--  gestiona en /admin/citas: pendiente / atendida / cancelada)
-- ============================================================
create table if not exists appointments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  city text not null default '',
  service text not null default '',
  preferred_date text not null default '',
  notes text not null default '',
  source text not null default 'terapia',
  status text not null default 'pendiente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists appointments_status_idx on appointments (status);
create index if not exists appointments_created_idx on appointments (created_at desc);
